server:
  port: 8080

spring:
  application:
    name: quiz-platform-backend

  data:
    mongodb:
      # Notice the space after 'uri:' and the 'quiz_platform' before the '?'
      uri: mongodb+srv://quizadmin:quizadmin2026@quizplatformcluster.sklenne.mongodb.net/quiz_platform?retryWrites=true&w=majority&appName=QuizPlatformCluster

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: quiz-platform-secret-key-should-be-long
  expiration: 3600000